python generate_depths.py --input_dir data/shiny_blender/ball/train
python generate_normals.py --input_dir data/shiny_blender/ball/train
python generate_depths.py --input_dir data/shiny_blender/car/train
python generate_normals.py --input_dir data/shiny_blender/car/train
python generate_depths.py --input_dir data/shiny_blender/coffee/train
python generate_normals.py --input_dir data/shiny_blender/coffee/train
python generate_depths.py --input_dir data/shiny_blender/helmet/train
python generate_normals.py --input_dir data/shiny_blender/helmet/train
python generate_depths.py --input_dir data/shiny_blender/teapot/train
python generate_normals.py --input_dir data/shiny_blender/teapot/train
python generate_depths.py --input_dir data/shiny_blender/toaster/train
python generate_normals.py --input_dir data/shiny_blender/toaster/train