python generate_depths.py --input_dir data/glossy_syn/angel/rgb
python generate_normals.py --input_dir data/glossy_syn/angel/rgb
python generate_depths.py --input_dir data/glossy_syn/bell/rgb
python generate_normals.py --input_dir data/glossy_syn/bell/rgb
python generate_depths.py --input_dir data/glossy_syn/cat/rgb
python generate_normals.py --input_dir data/glossy_syn/cat/rgb
python generate_depths.py --input_dir data/glossy_syn/horse/rgb
python generate_normals.py --input_dir data/glossy_syn/horse/rgb
python generate_depths.py --input_dir data/glossy_syn/luyu/rgb
python generate_normals.py --input_dir data/glossy_syn/luyu/rgb
python generate_depths.py --input_dir data/glossy_syn/potion/rgb
python generate_normals.py --input_dir data/glossy_syn/potion/rgb
python generate_depths.py --input_dir data/glossy_syn/tbell/rgb
python generate_normals.py --input_dir data/glossy_syn/tbell/rgb
python generate_depths.py --input_dir data/glossy_syn/teapot/rgb
python generate_normals.py --input_dir data/glossy_syn/teapot/rgb